[project]
name = "modularity-cli"
version = "0.1.0"
description = "CLI tool for Modularity"
authors = [
    { name = "Modularity Contributors" }
]
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.7",
    "rich>=13.7.0",
    "requests>=2.31.0",
    "pyyaml>=6.0.1",
]

[project.scripts]
modularity = "modularity_cli.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
