[project]
name = "modularity-registry"
version = "0.1.0"
description = "Modularity Registry Service"
authors = [
    { name = "Modularity Contributors" }
]
requires-python = ">=3.9"
dependencies = [
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
    "requests>=2.31.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false  # This is an application, not a library
